### ISSUE TITLE
Can't be installed due to requirement of (non-existent) Complete::Getopt::Long 0.479

### ISSUE THREAD

**Issue by cub-uanic** [perlancar/perl-Perinci-Sub-Complete#1]
The latest available Complete::Getopt::Long is 0.478: https://metacpan.org/release/Complete-Getopt-Long
So Perinci::Sub::Complete can't be installed unless the Complete::Getopt::Long of the previous version is already installed (for ex, see http://www.cpantesters.org/cpan/report/b87d2228-b808-11ea-a319-193bcccccfd6)

**Comment by eserte** [comment]
As the test suite passes with Complete::Getopt::Long 0.478 it is likely that either the test coverage is too low (i.e. the reason for requiring 0.479 instead of 0.478 was not tested), or the prereq version requirement is simply too high here.

**Comment by cub-uanic** [comment]
Not sure what you wanted to tell.

In this repo the version is 0.942: https://github.com/perlancar/perl-Perinci-Sub-Complete/blob/master/dist.ini
And required Complete::Getopt::Long is 0.476

On the CPAN the version is 0.943: https://metacpan.org/source/PERLANCAR/Perinci-Sub-Complete-0.943/dist.ini
And required Complete::Getopt::Long is 0.479

So there is a version on CPAN that is not yet in this repo.
The author has updated the sources and not yet pushed a fresh version to GitHub, but published it to the CPAN.

Without the author, this can't be solved, anyway.

**Comment by eserte** [comment]
Well, in the meantime Complete::Getopt::Long 0.479 exists (again; maybe it was removed due to an indexing accident), so probably this issue is obsolete.

**Comment by perlancar** [comment]
Sorry for the late response, didn't see the notification.

I believe this issue has been self-resolved.
